<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DMA-WKS15" name="com.newdemo.test.CM_Scenarios" tests="1" failures="1" timestamp="1 Nov 2018 17:32:36 GMT" time="0.003" errors="0">
  <testcase name="PositiveFlow_1_CMAndMPIntegration_ApproveNo" time="0.003" classname="com.newdemo.test.CM_Scenarios">
    <failure type="java.io.FileNotFoundException" message=".\Results\11-01-2018\11-01-2018_10-32_AM\ModuleRunResult 11-01-2018 10-32 AM.html (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: .\Results\11-01-2018\11-01-2018_10-32_AM\ModuleRunResult 11-01-2018 10-32 AM.html (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.PrintWriter.<init>(Unknown Source)
	at java.io.PrintWriter.<init>(Unknown Source)
	at com.newdemo.framework.base.HTMLFunctions.CreateResultFile(HTMLFunctions.java:108)
	at com.newdemo.framework.base.ScriptBase.LaunchBrowser(ScriptBase.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- PositiveFlow_1_CMAndMPIntegration_ApproveNo -->
</testsuite> <!-- com.newdemo.test.CM_Scenarios -->
